author: PenguinMan
description: "Very LightWeight plugin allows creating Redeemable Money Tokens"
main: me.Penguin.moneytoken.Main
name: MoneyTokens
version: 1.0.0
depend: [SuperPenguinCore]
api-version: 1.16

commands:

  moneytoken:
    aliases: [mt]
    
  coinvault:
    aliases: [cv]


permissions: 
    
  moneytokens.admin:
    default: op
    